buttlyzer.channel_list = ["all channels",
                          "#buttbottrivia",
                          "#internbotdebug",
                          "#internbotdebug2",
                          "#internhearts",
                          "#interns",
                          "#internsbotdebug2",
                          "#runescape"];

buttlyzer.channel_map = {"all channels": 0,
                         "#buttbottrivia": 1,
                         "#internbotdebug": 2,
                         "#internbotdebug2": 3,
                         "#internhearts": 4,
                         "#interns": 5,
                         "#internsbotdebug2": 6,
                         "#runescape": 7};

buttlyzer.user_array = ["all users",
                        "_",
                        "____________",
                        "_____________",
                        "`",
                        "^",
                        "a_cat",
                        "a_fulltimer_spying",
                        "ahmerz",
                        "ahmmaged",
                        "ahmmaged_",
                        "ahmmaged1",
                        "ahmmaged2",
                        "ahmmaged3",
                        "amylee",
                        "anguslim",
                        "anguslim|butts",
                        "asdf",
                        "blitzbot",
                        "buttbot",
                        "cendecki",
                        "cendecki_",
                        "certainly_a_cat",
                        "debugbot",
                        "definitely-not-blitz",
                        "deolanka",
                        "dickbot",
                        "dkieren",
                        "erictam",
                        "euank",
                        "galliher",
                        "grimesmg",
                        "grimesmg_",
                        "grimesmg1",
                        "gurbird",
                        "gurbird_",
                        "gurbird__",
                        "hyndman",
                        "hyndman_",
                        "jansohnh",
                        "jansohnh1",
                        "jansohnh4",
                        "jcchutko",
                        "jcchutko_",
                        "jruby",
                        "lamy",
                        "manelaj",
                        "matarnol",
                        "menyan",
                        "menyan_",
                        "menyan1",
                        "not_a_cat",
                        "not_a_cat__",
                        "notanguslim",
                        "other-grimesmg",
                        "owlbot",
                        "pisanis",
                        "pisanis1",
                        "probably_a_cat",
                        "qifan",
                        "reimerv",
                        "reimerv__bot",
                        "reimerv_bot",
                        "reimervbot",
                        "rhellybot",
                        "roflbot",
                        "saudalal",
                        "saudalal_",
                        "saudalal__",
                        "testbot",
                        "Trivia",
                        "triviabot",
                        "TriviaChampionpisani",
                        "volkman",
                        "xiao"];

buttlyzer.user_map = {"all users over all time": -1,
                      "all users": 0,
                      "_": 1,
                      "____________": 2,
                      "_____________": 3,
                      "`": 4,
                      "^": 5,
                      "a_cat": 6,
                      "a_fulltimer_spying": 7,
                      "ahmerz": 8,
                      "ahmmaged": 9,
                      "ahmmaged_": 10,
                      "ahmmaged1": 11,
                      "ahmmaged2": 12,
                      "ahmmaged3": 13,
                      "amylee": 14,
                      "anguslim": 15,
                      "anguslim|butts": 16,
                      "asdf": 17,
                      "blitzbot": 18,
                      "buttbot": 19,
                      "cendecki": 20,
                      "cendecki_": 21,
                      "certainly_a_cat": 22,
                      "debugbot": 23,
                      "definitely-not-blitz": 24,
                      "deolanka": 25,
                      "dickbot": 26,
                      "dkieren": 27,
                      "erictam": 28,
                      "euank": 29,
                      "galliher": 30,
                      "grimesmg": 31,
                      "grimesmg_": 32,
                      "grimesmg1": 33,
                      "gurbird": 34,
                      "gurbird_": 35,
                      "gurbird__": 36,
                      "hyndman": 37,
                      "hyndman_": 38,
                      "jansohnh": 39,
                      "jansohnh1": 40,
                      "jansohnh4": 41,
                      "jcchutko": 42,
                      "jcchutko_": 43,
                      "jruby": 44,
                      "lamy": 45,
                      "manelaj": 46,
                      "matarnol": 47,
                      "menyan": 48,
                      "menyan_": 49,
                      "menyan1": 50,
                      "not_a_cat": 51,
                      "not_a_cat__": 52,
                      "notanguslim": 53,
                      "other-grimesmg": 54,
                      "owlbot": 55,
                      "pisanis": 56,
                      "pisanis1": 57,
                      "probably_a_cat": 58,
                      "qifan": 59,
                      "reimerv": 60,
                      "reimerv__bot": 61,
                      "reimerv_bot": 62,
                      "reimervbot": 63,
                      "rhellybot": 64,
                      "roflbot": 65,
                      "saudalal": 66,
                      "saudalal_": 67,
                      "saudalal__": 68,
                      "testbot": 69,
                      "Trivia": 70,
                      "triviabot": 71,
                      "TriviaChampionpisani": 72,
                      "volkman": 73,
                      "xiao": 74};
